server:
  port: 8080
spring:
  application:
    name: mic-bff
rest-client:
  job-offer:
    host: http://localhost:8081/api/job-offers
  corporate-organization:
    host: http://localhost:8082/api/users
