server:
  port: 8080
spring:
  application:
    name: mic-bff
  mvc:
    servlet:
      path: /bff
rest-client:
  job-offer:
    host: http://localhost:8081/job-offer
  corporate-organization:
    host: http://localhost:8086/corporate-organization
azure:
  storage:
    connection-string: DefaultEndpointsProtocol=https;AccountName=antharos;AccountKey=IOxTIv6pzk3gZrAQzZ9Sq0w+nGhgCsfcLSNrQfTrT7eMwluoLR4r+9H4qrvFKjAYPr3I47OyKQZ1+AStLH6m8A==;EndpointSuffix=core.windows.net
