rest-client:
  job-offer:
    host: https://mic-joboffer.mangocliff-d23e761b.westeurope.azurecontainerapps.io/job-offer
  corporate-organization:
    host: https://mic-corporateorganization.mangocliff-d23e761b.westeurope.azurecontainerapps.io/corporate-organization
  analytics:
    host: https://mic-analytics.mangocliff-d23e761b.westeurope.azurecontainerapps.io/analytics
  aiintegrations:
    host: https://mic-aiintegrations.mangocliff-d23e761b.westeurope.azurecontainerapps.io/aiintegrations
cors:
  allowed-origins:
    - http://localhost:5173
    - http://spa-antharos.mangocliff-d23e761b.westeurope.azurecontainerapps.io
    - https://spa-antharos.mangocliff-d23e761b.westeurope.azurecontainerapps.io
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}