server:
  port: 8080
spring:
  application:
    name: mic-bff
  mvc:
    servlet:
      path: /bff
rest-client:
  job-offer:
    host: http://localhost:8081/job-offer
  corporate-organization:
    host: http://localhost:8086/corporate-organization
  analytics:
    host: http://localhost:8082/analytics
azure:
  storage:
    connection-string: DefaultEndpointsProtocol=https;AccountName=antharos;AccountKey=IOxTIv6pzk3gZrAQzZ9Sq0w+nGhgCsfcLSNrQfTrT7eMwluoLR4r+9H4qrvFKjAYPr3I47OyKQZ1+AStLH6m8A==;EndpointSuffix=core.windows.net
    container-name: cvs
logging:
  level:
    reactor.netty.http.client: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 21600000 # 6h in millisecond